_target_: federated_methods.fedrep.fedrep.FedRep
strategy: base # base, sharded, filter. See strategy.py for details
ckpt_path: null
server_test: False

# FedREP params:
warmup_rounds: 12 # amount fedavg rounds for warmup