_target_: federated_datasets.ptbxl_dataset.PTBXLDataset
data_sources:
  test_map_file: ["/home/ecg_data/physionet_data/ptbxl_data_1_0_3/test_map_ptbxl.csv"]
  train_map_file: ["/home/ecg_data/physionet_data/ptbxl_data_1_0_3/train_split_map_ptbxl.csv",
                   "/home/ecg_data/physionet_data/ptbxl_data_1_0_3/valid_split_map_ptbxl.csv"]
dataset_cfg:
  augmentation:
    transforms: null

  frequency: 500 # 500, 100
  
  # You may not be able to teach on all 12 leads
  leads: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
  
  # You can merge several pathologies into one by merge_map
  merge_map: {} 
  pathology_names: [AFIB, PVC, CRBBB]
  
  task_type: scp_codes
  norm_type: z_norm
  validated_by_human: false
  use_metadata: false
base_path: 'data'
mode: train
